services:
  - type: web
    name: monblog
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn monblog.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: monblog.settings
      - key: DATABASE_URL
        fromDatabase:
          name: monblog-db
          property: connectionString

databases:
  - name: monblog-db
    databaseName: monblog
    user: monblog_user
